/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Kevin Simon (aka: Snerfoil)
 */
public class windowHandle extends javax.swing.JFrame {

    private Boolean toggle0 = true;
    private Boolean toggle1 = true;
    private Boolean toggle2 = true;
    private int buttonPoll = 0;
    private static Blit myMap;
    /**
     * Creates new form windowHandle
     * the first 3 strings define the names of the map markers
     * the next string is the map directory
     * and the last one initalizes the card image.
     */
    public windowHandle(String a,String b,String c,String d,String e) {
	myMap = new Blit(a,b,c,d);
	this.setTitle("Game?");//change the title if you wana
	initComponents();
	this.changeCardIcon(e);
	jScrollPane1.getViewport().add(myMap, WIDTH);
	this.pack();
	this.setVisible(true);
    }
    /**
     * These functions can be used to manipulate the window
     * change the card image,
     * print out to the in-window console
     * change the scoreboard
     * and gather the player's button input
     * as well as a few other things.
     */
    public void changeCardIcon(String x){cardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(x)));}//dumpy method to change the card icon
    public void consoleOut(String x){consoleArea.setText(consoleArea.getText() +"\n"+ x);}//print text, ya know the drill
    public void setScoreBoard(String x){scoreArea.setText(x);}//change the displayed text in the scoreboard, does not add.
    public void setList(String[] x){moveList.setListData(x);}//change the list data
    public String getListChoice(){return moveList.getSelectedValue();}//so what did he pick?
    public void deselect(){moveList.clearSelection();}//deselect, durr....
    public void drawToggle(){// toggle the drawbutton
	toggle0 = !toggle0;
	drawButton.setEnabled(toggle0);
    }
    public void moveToggle(){// toggle the movebutton
	toggle1 = !toggle1;
	moveButton.setEnabled(toggle1);
    }
    public void playToggle(){// toggle the playbutton
	toggle2 = !toggle2;
	playButton.setEnabled(toggle2);
    }
    public void move0(int x,int y){myMap.move0(x,y);}//reposition the first label
    public void move1(int x,int y){myMap.move1(x,y);}//reposition the second label
    public void move2(int x,int y){myMap.move2(x,y);}//reposition the third label
    //remember that the names are drawn from the lower left corner
    public int getPoll(){
	int x = 0;
	while(x==0){
	    x = buttonPoll;
	    System.out.print("");
	    //logically this above statement does not affect the function's function
	    //but without it, IT WILL NOT WORK FOR SOME REASON.
	    //i'll be amazed if you can figure out why thats the case.
	}
	buttonPoll=0;
	return x;
    }//waits for the user to press one of the buttons.
    //and returns an integer representing the button pressed
    // there are 4 buttons
    // 0 is invalid, the loop cant complete with this value
    // 1 is the DRAW button
    // 2 is the PLAY button
    // 3 is the MOVE button
    // 4 is the picture (its also a button)

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")// this is all black magic
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        drawButton = new javax.swing.JButton();
        moveButton = new javax.swing.JButton();
        playButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        moveList = new javax.swing.JList<>();
        cardLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        scoreArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        consoleArea = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        drawButton.setText("DRAW");
        drawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawButtonActionPerformed(evt);
            }
        });

        moveButton.setText("MOVE");
        moveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveButtonActionPerformed(evt);
            }
        });

        playButton.setText("PLAY");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        moveList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "These", "are", "Strings", "in a ", "List" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(moveList);

        cardLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardLabelMouseClicked(evt);
            }
        });

        scoreArea.setEditable(false);
        scoreArea.setColumns(20);
        scoreArea.setRows(5);
        scoreArea.setText("scores?");
        scoreArea.setToolTipText("This is the scoreboard");
        jScrollPane3.setViewportView(scoreArea);

        consoleArea.setEditable(false);
        consoleArea.setColumns(20);
        consoleArea.setRows(5);
        consoleArea.setText("consoleoutput");
        consoleArea.setToolTipText("this is what has happend so far");
        jScrollPane4.setViewportView(consoleArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(drawButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(drawButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cardLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
	buttonPoll = 3;
    }//GEN-LAST:event_playButtonActionPerformed

    private void drawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawButtonActionPerformed
	buttonPoll = 1;
    }//GEN-LAST:event_drawButtonActionPerformed

    private void moveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveButtonActionPerformed
	buttonPoll = 2;
    }//GEN-LAST:event_moveButtonActionPerformed

    private void cardLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardLabelMouseClicked
	buttonPoll = 4;
    }//GEN-LAST:event_cardLabelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cardLabel;
    private javax.swing.JTextArea consoleArea;
    private javax.swing.JButton drawButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton moveButton;
    private javax.swing.JList<String> moveList;
    private javax.swing.JButton playButton;
    private javax.swing.JTextArea scoreArea;
    // End of variables declaration//GEN-END:variables
}
